"""Regenerates docs/DATABASE.md from a migrated database. Usage: PGHOST=... PGUSER=... PGDATABASE=... python3 tools/gen-db-doc.py"""
import subprocess, collections, os, glob
def q(sql):
    return [l.split('|') for l in subprocess.run(['psql', '-At', '-F', '|', '-c', sql], capture_output=True, text=True, check=True).stdout.strip().splitlines()]
cols = q("""SELECT c.table_name, c.column_name, c.data_type, c.is_nullable, COALESCE(c.column_default,'') FROM information_schema.columns c JOIN information_schema.tables t USING (table_schema, table_name)
WHERE c.table_schema='public' AND t.table_type='BASE TABLE' ORDER BY c.table_name, c.ordinal_position""")
fks = q("""SELECT tc.table_name, kcu.column_name, ccu.table_name, ccu.column_name FROM information_schema.table_constraints tc JOIN information_schema.key_column_usage kcu ON tc.constraint_name=kcu.constraint_name
JOIN information_schema.constraint_column_usage ccu ON tc.constraint_name=ccu.constraint_name WHERE tc.constraint_type='FOREIGN KEY' AND tc.table_schema='public'""")
fk = {(a, b): f'{c}.{d}' for a, b, c, d in fks}
purpose = {
 'companies': 'Group companies: operating, registered and visa-sponsoring (§5).', 'departments': 'Departments and branches (§5).', 'locations': 'Branches / operating locations (§5).',
 'asset_categories': 'Vehicle / machine categories; new ones need no code change (§2.2).', 'users': 'Sign-in accounts, role and organisational scope (§4). Passwords are bcrypt hashes.',
 'sessions': 'Server-side sessions (hashed tokens), revocable.', 'document_types': 'Configurable document types: module, expiry behaviour, required-for, thresholds, responsible officer (§5, §10).',
 'files': 'Metadata of stored scans and photos. The bytes live in FILES_DIR under a system key, never at a public URL (§9).',
 'employees': 'Employee master (§6.1).', 'assets': 'Vehicle / machine master (§8.1).', 'documents': 'One row per owner + document type; the logical document (§9).',
 'document_versions': 'Every version of a document. Exactly one is current; renewals supersede and keep history (§9).',
 'expiry_actions': 'Attention items / renewal actions: assignee, status, completion (§10).', 'action_events': 'Status history of each renewal action.',
 'leave_requests': 'Leave transactions and rejoining (§7).', 'leave_events': 'Decision trail of each leave request.', 'notification_templates': 'Alert text per event (§5).',
 'notifications': 'In-app alerts and e-mail delivery state, de-duplicated (§10).', 'system_config': 'System settings edited in Administration.',
 'audit_events': 'Append-only audit trail; a trigger refuses UPDATE and DELETE (§4.1).', 'ai_interactions': 'Log of AI questions, the path that answered and the record references returned (§12).',
 'job_runs': 'Background job history for monitoring (§15).', 'import_batches': 'Data import batches with accepted / rejected counts (§16).', 'schema_migrations': 'Applied database migrations.',
 'data_version': 'Change counter bumped by triggers on every write to records, documents, files and actions; drives the in-memory record cache.'}
migs = ', '.join(f'`{os.path.basename(m)}`' for m in sorted(glob.glob(os.path.join(os.path.dirname(__file__), '..', 'server', 'migrations', '*.sql'))))
by = collections.OrderedDict()
for t, c, ty, n, d in cols: by.setdefault(t, []).append((c, ty, n, d))
out = ['# Database reference', '', f'PostgreSQL 16. Generated by `tools/gen-db-doc.py` from the live schema after migrations {migs}. Internal IDs are immutable; business IDs (employee no., fleet no.) are separate and unique (§13.1).', '',
       '| Table | Purpose |', '|---|---|'] + [f'| `{t}` | {purpose.get(t, "")} |' for t in by] + ['']
for t, cs in by.items():
    out += [f'## {t}', '', purpose.get(t, ''), '', '| Column | Type | Null | Default / reference |', '|---|---|---|---|']
    for c, ty, n, d in cs:
        ref = f'→ `{fk[(t, c)]}`' if (t, c) in fk else (f'`{d[:40]}`' if d else '')
        out.append(f'| `{c}` | {ty} | {"yes" if n == "YES" else "no"} | {ref} |')
    out.append('')
open(os.path.join(os.path.dirname(__file__), '..', 'docs', 'DATABASE.md'), 'w').write('\n'.join(out))
print(len(by), 'tables')
